# -*- coding: utf-8 -*-
"""Data_cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SkpKJqyNLDbVjRYawveLq4CQsMk5a2M
"""

import pandas as pd
import numpy as np

# 1. Access/Load the dataset
df = pd.read_csv('/content/A_Passenger_Survey.csv')

# 2. Show all original column names on the terminal
# print("--- Original Columns ---")
# for col in df.columns:
#     print(col)

# # 3. Drop the 3 unnecessary columns
# # We use inplace=True so it modifies the dataframe directly without needing to reassign it
columns_to_drop = ['Timestamp', 'Gender.1', 'Column 25']
df.drop(columns=columns_to_drop, inplace=True)

# # 4. Show the column names again to verify they are gone
print("\n--- Columns After Dropping ---")
for col in df.columns:
    print(col)

#renameing the colums (snake_case)
df.columns = df.columns.str.strip()
rename_mapping = {
    'Gender': 'gender',
    'Age Group': 'age_group',
    'Occupation': 'occupation',
    'Monthly Household Income (BDT)': 'income_bdt',
    'Which area of Dhaka do you live in?': 'residential_area',
    'What was your primary mode of transport for this specific trip BEFORE MRT Line-6 became available on this route?': 'prev_transport_mode',
    'Do you currently use MRT Line-6 as your primary mode for this trip?': 'is_metro_primary_now',
    'What is your primary trip purpose when using this route?': 'trip_purpose',
    'Do you own a private vehicle (car, motorcycle or bicycle)?': 'owns_private_vehicle',
    'Approximately how long does your total trip take (in minutes) by metro, including walking to and from the station? \nNote: If you use Metro': 'metro_trip_time_mins',
    'Approximately how long did your total trip take using your previous mode of transport? (in minutes)': 'prev_trip_time_mins',
    'What is your approximate one-way fare for this trip by metro (BDT)?  \nNote: If you use Metro': 'metro_fare_bdt',
    'How far is the nearest MRT Line-6 station from your home or trip origin? (walking time)': 'walk_time_to_station',
    'How do you typically travel from your home to the metro station?': 'access_mode_to_station',
    'After getting off the metro, how long does it take you to reach your final destination?': 'egress_time_to_dest',
    'How do you travel from the metro station to your final destination?': 'egress_mode_to_dest',
    'Have you ever used MRT Line 6 at least once?': 'ever_used_metro',
    'Travel time': 'rating_travel_time',
    'Comfort': 'rating_comfort',
    'Reliability/Punctuality': 'rating_reliability',
    'Safety': 'rating_safety',
    'Fare/Cost': 'rating_fare',
    'What is the main reason you have not switched to MRT Line-6 as your primary mode? (Only if you have chosen "No" or "occasionally" for the previous question.)': 'reason_not_switched',
    'What is the main reason you have switched to MRT Line-6 as your primary mode? (Only if you have chosen "Yes" for the previous question.)': 'reason_switched',
    'Approximately what was your one-way fare using your previous mode of transport (BDT)?': 'prev_fare_bdt',
    'How often do you use metro?': 'metro_usage_frequency',
    'Ticketing system': 'rating_ticketing_system'
}
df.rename(columns=rename_mapping, inplace=True)

df.head()

for col in df.columns:
    print(col)

col = 'rating_ticketing_system'

print(f"--- {col} ---")
print("Unique list:", df[col].unique())
print("\nFrequency count:")
print(df[col].value_counts(dropna=False))

# removing spaces after the answer for each columns
df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
print(df['occupation'].unique())

#merging semantics
# Define how we want to group the tiny categories into the main ones
occupation_mapping = {
    # 1. Keep the main ones as they are (or explicitly map them)
    'Student': 'Student',
    'Government employee': 'Government employee',
    'Business owner': 'Business owner',
    'Homemaker': 'Homemaker',

    # 2. Cluster all corporate, service, and gig workers into "Private sector"
    'Private sector employee': 'Private sector employee',
    'Salesperson': 'Government employee',
    'Salesman': 'Private sector employee',
    'Cashier': 'Private sector employee',
    'Guard': 'Private sector employee',
    'Cleaner': 'Government employee',
    'Driver': 'Government employee',
    'Rider': 'Private sector employee',
    'Caretaker': 'Private sector employee',
    'Hair dresser': 'Private sector employee',
    'Makeup Artist': 'Private sector employee',
    'Cook': 'Private sector employee',

    # 3. Cluster educators and professionals (You can put these in Private or Govt, I'll put them in Private for now)
    'Teacher': 'Private sector employee',
    'School teacher': 'Government employee',
    'Tutor': 'Private sector employee',
    'Lawyer': 'Private sector employee',

    # 4. Cluster people not currently in the workforce
    'Unemployed': 'Unemployed',
    'Retired': 'Retired',
    'Retired Army Officer': 'Retired'
}

# Apply the mapping to the column
df['occupation'] = df['occupation'].map(occupation_mapping)

# Check the new, clean breakdown
print(df['occupation'].value_counts(dropna=False))

#converting random text response to nan
df['prev_transport_mode'] = df['prev_transport_mode'].replace('Did not make this trip regularly before metro', "N/A")
print(df['prev_transport_mode'].value_counts(dropna=False))

#cleaning area issue
def clean_area(area):
    # Skip null values if they exist
    if pd.isna(area):
        return area

    # Convert to lowercase to ignore capitalization
    a_lower = area.lower().strip()

    if 'motijheel' in a_lower:
        return 'Motijheel'

    if 'mohakhali' in a_lower:
        return 'Mohakhali Intersection'

    if a_lower == 'south':
        return 'Uttara South'

    if 'uttara' in a_lower or 'uttor' in a_lower or a_lower == 'north':
        return 'Uttara North'

    return area

# Apply the function to your column
df['residential_area'] = df['residential_area'].apply(clean_area)

# Check the new frequency count!
print(df['residential_area'].value_counts(dropna=False))

# ordinal scale transformation
# 1. Define the ordinal spectrum (Lowest adoption to Highest)
adoption_mapping = {
    'No, I still primarily use my previous mode': '1 - Non-Switcher',
    'I use metro only occasionally': '2 - Marginal User',
    'Yes, I use metro more often than my previous mode': '3 - Partial Switcher',
    'Yes, I have completely switched to metro': '4 - Full-Switcher'
}

# 2. Apply the mapping to overwrite the old bulky text
df['is_metro_primary_now'] = df['is_metro_primary_now'].map(adoption_mapping)

# 3. Print the results sorted by the index to see the perfect ordinal progression!
print(df['is_metro_primary_now'].value_counts(dropna=False).sort_index())

#clustering semantics
replace = {
'Work':'work',
'Education':'education',
'personal errands ':'personal errands',
'Healthcare':'Healthcare',
'Shopping':'personal errands',
'Childrens\' education': 'personal errands',
'Picking up and dropping off kids at school':'personal errands',
'Business':'work'
}
df['trip_purpose'] = df['trip_purpose'].map(replace)

# Check the new, clean breakdown
print(df['trip_purpose'].value_counts(dropna=False))

# fixing vehicle distribution and creating four new columns
df['owns_car'] = df['owns_private_vehicle'].str.contains('car', case=False, na=False)
df['owns_motorcycle'] = df['owns_private_vehicle'].str.contains('motorcycle', case=False, na=False)
df['owns_bicycle'] = df['owns_private_vehicle'].str.contains('bicycle', case=False, na=False)

df['owns_any_vehicle'] = np.where(df['owns_car'] | df['owns_motorcycle'] | df['owns_bicycle'], 'Yes', 'No')

df.drop(columns=['owns_private_vehicle'], inplace=True)

#clustering semantics
replace = {
'Varsity bus service': 'University bus service',
'Varsity bus': 'University bus service',
'My route is not well served by Line-6':'My route is not well served by Line-6',
'Station is too far from my origin or destination': 'Station is too far from my origin or destination',
'Metro fare is too expensive compared to my previous mode':'Metro fare is too expensive compared to my previous mode',
'I have a personal vehicle':'I have a personal vehicle',
'Travel time by metro is not faster for my trip':'Travel time by metro is not faster for my trip',
'Comfort or crowding concerns':'Comfort or crowding concerns'
}
df['reason_not_switched'] = df['reason_not_switched'].map(replace)

# Check the new, clean breakdown
print(df['reason_not_switched'].value_counts(dropna=False))

# Define who is who based on our ordinal column
switchers = df['is_metro_primary_now'].isin(['3 - Primary Metro User', '4 - Complete Switcher'])
non_switchers = df['is_metro_primary_now'].isin(['1 - Primary Previous Mode', '2 - Occasional Metro User'])
# If you switched, wipe any answer in 'reason_not_switched'
df.loc[switchers, 'reason_not_switched'] = np.nan
# If you didn't switch, wipe any answer in 'reason_switched'
df.loc[non_switchers, 'reason_switched'] = np.nan

# Group 1 (Primary Previous Mode) should NOT have metro time or fare for this commute
group_1 = df['is_metro_primary_now'] == '1 - Primary Previous Mode'
#Force Time and Fare to NaN for Group 1
df.loc[group_1, 'metro_trip_time_mins'] = np.nan
df.loc[group_1, 'metro_fare_bdt'] = np.nan
# Used metro or no
used_metro = df['ever_used_metro'].str.strip().str.lower() == 'yes'
never_used = df['ever_used_metro'].str.strip().str.lower() == 'no'
#If they NEVER used the metro, they cannot have station travel data. Wipe it.
cols_to_wipe = ['access_mode_to_station', 'egress_time_to_dest', 'egress_mode_to_dest']
df.loc[never_used, cols_to_wipe] = np.nan

ghost_cols = [
    'rating_travel_time',
    'rating_comfort',
    'rating_reliability',
    'rating_safety',
    'rating_fare',
    'rating_ticketing_system',
    'metro_trip_time_mins',
    'metro_fare_bdt',
    'metro_usage_frequency'
]
# checks if ANY of the columns in that list have a value for that row
violations = never_used & df[ghost_cols].notna().any(axis=1)
print(f"Ghost Riders Found: {violations.sum()}")
# Wipe those specific columns for the never_used group
df.loc[never_used, ghost_cols] = np.nan

prev_mode = df['prev_transport_mode'].str.strip().str.lower()
access_mode = df['access_mode_to_station'].str.strip().str.lower()
egress_mode = df['egress_mode_to_dest'].str.strip().str.lower()
# Isolate the specific violations
viol_car = (prev_mode == 'private car') & (df['owns_car'] == False)
viol_moto = (prev_mode == 'motorcycle') & (df['owns_motorcycle'] == False)
viol_bike = (prev_mode == 'bicycle') & (df['owns_bicycle'] == False)

viol_any_veh = ((access_mode == 'personal vehicle') | (egress_mode == 'personal vehicle')) & (df['owns_any_vehicle'] == 'No')
# Define the exact label you want to use
ride_share_label = 'Ride Share'
# Change the impossible previous modes to Ride Share
df.loc[viol_car | viol_moto | viol_bike, 'prev_transport_mode'] = ride_share_label
# Change the impossible first/last mile modes to Ride Share
df.loc[viol_any_veh & (access_mode == 'personal vehicle'), 'access_mode_to_station'] = ride_share_label
df.loc[viol_any_veh & (egress_mode == 'personal vehicle'), 'egress_mode_to_dest'] = ride_share_label

#fixing time math calculation
# Map the lower bounds for the first and last mile
walk_min = {
    'Less than 5 minutes': 0,
    '5–10 minutes': 5,
    '11–15 minutes': 11,
    'More than 15 minutes': 16
}

egress_min = {
    '< 5 min': 0,
    '5–10 min': 5,
    '11–15 min': 11,
    '> 15 min': 16
}
# Find Metro Users who are missing their total trip time
used_metro = df['ever_used_metro'].str.strip().str.lower() == 'yes'
missing_total = used_metro & df['metro_trip_time_mins'].isna()
# Calculate their Estimated Minimum Time
# We take their walk + egress + 10 mins (conservative estimate for train + waiting)
walk = df.loc[missing_total, 'walk_time_to_station'].map(walk_min)
egress = df.loc[missing_total, 'egress_time_to_dest'].map(egress_min)
estimated_time_mins = walk + egress + 10
# Function to convert the raw number back into your survey's exact categories
def categorize_time(mins):
    if pd.isna(mins):
        return np.nan
    elif mins < 15:
        return 'Less than 15'
    elif mins <= 30:
        return '15-30'
    elif mins <= 45:
        return '31-45'
    elif mins <= 60:
        return '46-60'
    else:
        return 'More than 60'

# Apply the function and fill the missing blanks in the original column
estimated_buckets = estimated_time_mins.apply(categorize_time)
df.loc[missing_total, 'metro_trip_time_mins'] = estimated_buckets

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
df.head(5)

df.to_csv('cleaded_survey_response.csv', index=False)
print("Data Imputed and Saved!")